# This file configures what is only needed for development of the ontohub app.
# It only concerns developers and is not needed/not loaded in any environment
# other than 'development'.

paths:
  # Hets environment. The first matching item in the lists is used.
  hets:
    executable:
      - /usr/bin/hets-server
      - /usr/local/bin/hets-server
      - /opt/local/bin/hets-server
      - /usr/local/opt/hets/bin/hets-server
      - /usr/local/opt/hets/bin/hets-bin-server
      - /usr/bin/hets
      - /usr/local/bin/hets
      - ~/dev/hets/hets
      - /opt/local/bin/hets
      - ~/code/hets/hets
      - ~/ontohub/Hets/hets
      - /usr/local/opt/hets/bin/hets
      - /usr/local/opt/hets/bin/hets-bin
      - /usr/local/opt/hets-binary/Hets.app/Contents/Resources/hets
      - /Applications/Hets.app/Contents/Resources/hets
    hets_lib:
      - /usr/lib/hets/hets-lib
      - ~/dev/hets/lib
      - ~/ontohub/Hets
      - /usr/local/opt/hets-lib
      - /usr/local/opt/hets-binary/Hets.app/Contents/Resources/Hets-lib
      - /Applications/Hets.app/Contents/Resources/Hets-lib
      - /opt/hets-lib
