# Put your test specific settings into this file

hostname: example.com
email: noreply@example.com
action_mailer:
  delivery_method: :test

paths:
  data: tmp/data
  git_repositories: tmp/data/git
  symlinks: tmp/data/git_daemon
  commits: tmp/data/commits
  git_home: tmp/git
